### ISSUE TITLE
Concurrency Control

### ISSUE THREAD

**Issue by devansh42** [shreybatra/crankdb#2]
Hey @shreybatra , How are you planning to handle concurrent commands?

**Comment by shreybatra** [comment]
Hey @devansh42 , currently you can connect with multiple clients and can fire multiple commands at same time. The server is smart enough to process them in goroutines (async light weight threads) concurrently. Obviously, there is no atomicity / transactions / mvcc architecture implemented as this is a very basic setup, but would extend the support soon.

Still, you can have concurrent commands fired even now :)
